//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int ID { get; set; }
        public int Category_ID { get; set; }
        public string Text { get; set; }
        public string Answer { get; set; }
        public bool IsDone { get; set; }
    }
}
